server:
  port: 8000
  error:
    include-message: always

spring:
  application:
    name: camel-microservice-b

#  activemq:
#    broker-url: tcp://localhost:61616
#
#camel:
#  component:
#    kafka:
#      brokers: http://localhost:9092